version: '3.7'

services:
  mysql:
    image: mariadb
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "password" # 任意で変更してください
      MYSQL_DATABASE: "drupal" # 任意で変更してください
      MYSQL_USER: "username" # 新たに追加したユーザ名
      MYSQL_PASSWORD: "userpassword" # 新たに追加したユーザのパスワード
    ports:
      - "3306:3306"

  drupal:
    build: ./
    volumes:
      - ./web/themes:/var/www/html/themes
      - ./web/modules:/var/www/html/modules
      - ./web/sites:/var/www/html/sites
      - ./config:/opt/drupal/config
      - ./composer.json:/opt/drupal/composer.json
      - ./composer.lock:/opt/drupal/composer.lock
    ports:
      - "80:80"
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8180:80"
    environment:
      PMA_USER: username
      PMA_PASSWORD: userpassword
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "password" # MySQLのパスワードと同じにしてください

volumes:
  data: {}
